---
apiVersion: v1
kind: Service
metadata:
  namespace: chefbe
  name: dans-en-muziek
  labels:
    name: dans-en-muziek
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dans-en-muziek
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dans-en-muziek
  namespace: chefbe
  annotations:
spec:
  rules:
  - host: www.dans-en-muziek.be
    http:
      paths:
      - path: /
        backend:
          serviceName: dans-en-muziek
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dans-en-muziek
  namespace: chefbe
  labels:
    app: dans-en-muziek
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dans-en-muziek
  template:
    metadata:
      labels:
        app: dans-en-muziek
    spec:
      imagePullSecrets:
      - name: q8s-pull-secret
      containers:
      - image: q8s.quadrabee.com/chefbe/dans-en-muziek
        name: dans-en-muziek
        env:
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 100
          periodSeconds: 20
        resources:
          requests:
            memory: "150Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
